#!/usr/bin/env python3
from src.game import Game
# from src.player import Player
from src.rooms.start import StartingRoom

print('Demo Starting')

game = Game()
game.setRoom(StartingRoom())
# game.setPlayer(Player())

game.start()
